### ISSUE TITLE
PDF sofar Communication Protocol

### ISSUE THREAD

**Issue by willyRed77** [pawelka/sofarsolar_esp_rs485_logger#28]
I've just to found a Communication Protocol file of sofar, at the moment i dont understand how to use it for measure, the energy I consume or feed into the grid. 

[PDF 1](https://solaranzeige.de/phpBB3/download/file.php?id=5254)

[PDF 2](https://community.openenergymonitor.org/uploads/short-url/dF8j79PsvtCS0xQ5aPxHXO4HZDE.pdf)

I hope you like it @pawelka.

Also i have had to change the attributtes in esphome config due to not possible to add to the energy monitoring with statistics that has home assistant. 
One example would be like this:

```
  - platform: modbus_controller
    modbus_controller_id: sofarsolar
    name: ${friendly_name} Energy today
    id: inverter_energy_today
    register_type: holding
    address: 0x0019
    unit_of_measurement: "kWh"
    device_class: "energy"
    state_class: "total_increasing"
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01
```

device_class and state class needed for the problem i said
The info for resolve this problem. https://www.home-assistant.io/docs/energy/faq/#troubleshooting-missing-entities
